name: PR Merged To Main Create Tag and Release
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from branch name
        id: extract_version
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          echo "Branch name: $BRANCH_NAME"
          
          # Extract version from release/x.x.x format
          if [[ $BRANCH_NAME =~ ^release/([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            VERSION="${BASH_REMATCH[1]}"
            TAG_NAME="v$VERSION"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
            echo "Extracted version: $VERSION"
            echo "Tag name: $TAG_NAME"
          else
            echo "Branch name does not match release/x.x.x pattern"
            exit 1
          fi

      - name: Create tag
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git tag ${{ steps.extract_version.outputs.tag_name }}
          git push origin ${{ steps.extract_version.outputs.tag_name }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_version.outputs.tag_name }}
          release_name: ${{ steps.extract_version.outputs.tag_name }}
          draft: false
          body: |
            Release ${{ steps.extract_version.outputs.tag_name }}
            
            Merged from PR: #${{ github.event.pull_request.number }}
            Branch: ${{ github.event.pull_request.head.ref }}
